[2022-10-28T22:45:00.429+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.delete_table manual__2022-10-28T22:44:41.937348+00:00 [queued]>
[2022-10-28T22:45:00.441+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.delete_table manual__2022-10-28T22:44:41.937348+00:00 [queued]>
[2022-10-28T22:45:00.441+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:45:00.441+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-28T22:45:00.441+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:45:00.460+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryDeleteTableOperator): delete_table> on 2022-10-28 22:44:41.937348+00:00
[2022-10-28T22:45:00.467+0000] {standard_task_runner.py:55} INFO - Started process 19506 to run task
[2022-10-28T22:45:00.473+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'carga_tb_carteira', 'delete_table', 'manual__2022-10-28T22:44:41.937348+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/carga_tb_carteira.py', '--cfg-path', '/tmp/tmplp5avbd4']
[2022-10-28T22:45:00.476+0000] {standard_task_runner.py:83} INFO - Job 88: Subtask delete_table
[2022-10-28T22:45:00.562+0000] {task_command.py:376} INFO - Running <TaskInstance: carga_tb_carteira.delete_table manual__2022-10-28T22:44:41.937348+00:00 [running]> on host cs-1097450612417-default
[2022-10-28T22:45:00.663+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=Marcelo Henrique
AIRFLOW_CTX_DAG_ID=carga_tb_carteira
AIRFLOW_CTX_TASK_ID=delete_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T22:44:41.937348+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-28T22:44:41.937348+00:00
[2022-10-28T22:45:00.665+0000] {bigquery.py:2326} INFO - Deleting: tech-visa-jobs.carteira_acoes.TB_CARTEIRA
[2022-10-28T22:45:00.681+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2327, in execute
    hook = BigQueryHook(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 99, in __init__
    super().__init__(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 226, in __init__
    self.extras = self.get_connection(self.gcp_conn_id).extra_dejson  # type: Dict
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `cofre_conn` isn't defined
[2022-10-28T22:45:00.709+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=carga_tb_carteira, task_id=delete_table, execution_date=20221028T224441, start_date=20221028T224500, end_date=20221028T224500
[2022-10-28T22:45:00.735+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 88 for task delete_table (The conn_id `cofre_conn` isn't defined; 19506)
[2022-10-28T22:45:00.765+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T22:45:00.791+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
