[2022-10-28T22:58:48.043+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.delete_table manual__2022-10-28T22:44:41.937348+00:00 [queued]>
[2022-10-28T22:58:48.056+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.delete_table manual__2022-10-28T22:44:41.937348+00:00 [queued]>
[2022-10-28T22:58:48.056+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:58:48.056+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 5
[2022-10-28T22:58:48.056+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:58:48.077+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryDeleteTableOperator): delete_table> on 2022-10-28 22:44:41.937348+00:00
[2022-10-28T22:58:48.084+0000] {standard_task_runner.py:55} INFO - Started process 22258 to run task
[2022-10-28T22:58:48.088+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'carga_tb_carteira', 'delete_table', 'manual__2022-10-28T22:44:41.937348+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/carga_tb_carteira.py', '--cfg-path', '/tmp/tmpjz6lbkqq']
[2022-10-28T22:58:48.091+0000] {standard_task_runner.py:83} INFO - Job 101: Subtask delete_table
[2022-10-28T22:58:48.168+0000] {task_command.py:376} INFO - Running <TaskInstance: carga_tb_carteira.delete_table manual__2022-10-28T22:44:41.937348+00:00 [running]> on host cs-1097450612417-default
[2022-10-28T22:58:48.224+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=Marcelo Henrique
AIRFLOW_CTX_DAG_ID=carga_tb_carteira
AIRFLOW_CTX_TASK_ID=delete_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T22:44:41.937348+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-28T22:44:41.937348+00:00
[2022-10-28T22:58:48.225+0000] {bigquery.py:2326} INFO - Deleting: tech-visa-jobs.carteira_acoes.TB_CARTEIRA
[2022-10-28T22:58:48.230+0000] {base.py:71} INFO - Using connection ID 'gcp_conn' for task execution.
[2022-10-28T22:58:48.426+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2333, in execute
    hook.delete_table(table_id=self.deletion_dataset_table, not_found_ok=self.ignore_if_missing)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 464, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1181, in delete_table
    self.get_client(project_id=project_id).delete_table(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1817, in delete_table
    self._call_api(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://bigquery.googleapis.com/bigquery/v2/projects/tech-visa-jobs/datasets/carteira_acoes/tables/TB_CARTEIRA?prettyPrint=false: Not found: Table tech-visa-jobs:carteira_acoes.TB_CARTEIRA
[2022-10-28T22:58:48.433+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=carga_tb_carteira, task_id=delete_table, execution_date=20221028T224441, start_date=20221028T225848, end_date=20221028T225848
[2022-10-28T22:58:48.448+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 101 for task delete_table (404 DELETE https://bigquery.googleapis.com/bigquery/v2/projects/tech-visa-jobs/datasets/carteira_acoes/tables/TB_CARTEIRA?prettyPrint=false: Not found: Table tech-visa-jobs:carteira_acoes.TB_CARTEIRA; 22258)
[2022-10-28T22:58:48.463+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T22:58:48.493+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
