[2022-10-28T22:48:45.660+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.criando_tabela_bigquery manual__2022-10-28T22:44:41.937348+00:00 [queued]>
[2022-10-28T22:48:45.671+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.criando_tabela_bigquery manual__2022-10-28T22:44:41.937348+00:00 [queued]>
[2022-10-28T22:48:45.671+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:48:45.671+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2022-10-28T22:48:45.671+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:48:45.690+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryCreateExternalTableOperator): criando_tabela_bigquery> on 2022-10-28 22:44:41.937348+00:00
[2022-10-28T22:48:45.696+0000] {standard_task_runner.py:55} INFO - Started process 20223 to run task
[2022-10-28T22:48:45.701+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'carga_tb_carteira', 'criando_tabela_bigquery', 'manual__2022-10-28T22:44:41.937348+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/carga_tb_carteira.py', '--cfg-path', '/tmp/tmpqp1ybav5']
[2022-10-28T22:48:45.704+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask criando_tabela_bigquery
[2022-10-28T22:48:45.766+0000] {task_command.py:376} INFO - Running <TaskInstance: carga_tb_carteira.criando_tabela_bigquery manual__2022-10-28T22:44:41.937348+00:00 [running]> on host cs-1097450612417-default
[2022-10-28T22:48:45.846+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=Marcelo Henrique
AIRFLOW_CTX_DAG_ID=carga_tb_carteira
AIRFLOW_CTX_TASK_ID=criando_tabela_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T22:44:41.937348+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-28T22:44:41.937348+00:00
[2022-10-28T22:48:45.853+0000] {base.py:71} INFO - Using connection ID 'gcp_conn' for task execution.
[2022-10-28T22:48:46.009+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1673, in execute
    table = bq_hook.create_empty_table(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 464, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 404, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 748, in create_table
    api_response = self._call_api(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/tech-visa-jobs/datasets/carteira_acoes/tables?prettyPrint=false: Invalid value for sourceFormat: csv is not a valid value
[2022-10-28T22:48:46.018+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=carga_tb_carteira, task_id=criando_tabela_bigquery, execution_date=20221028T224441, start_date=20221028T224845, end_date=20221028T224846
[2022-10-28T22:48:46.046+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 98 for task criando_tabela_bigquery (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/tech-visa-jobs/datasets/carteira_acoes/tables?prettyPrint=false: Invalid value for sourceFormat: csv is not a valid value; 20223)
[2022-10-28T22:48:46.075+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T22:48:46.091+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
