[2022-10-28T22:29:45.857+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.criando_tabela_bigquery manual__2022-10-28T22:28:57.533945+00:00 [queued]>
[2022-10-28T22:29:45.868+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: carga_tb_carteira.criando_tabela_bigquery manual__2022-10-28T22:28:57.533945+00:00 [queued]>
[2022-10-28T22:29:45.868+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:29:45.868+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-10-28T22:29:45.869+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:29:45.887+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryCreateExternalTableOperator): criando_tabela_bigquery> on 2022-10-28 22:28:57.533945+00:00
[2022-10-28T22:29:45.892+0000] {standard_task_runner.py:55} INFO - Started process 16470 to run task
[2022-10-28T22:29:45.898+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'carga_tb_carteira', 'criando_tabela_bigquery', 'manual__2022-10-28T22:28:57.533945+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/carga_tb_carteira.py', '--cfg-path', '/tmp/tmpn1moxne8']
[2022-10-28T22:29:45.901+0000] {standard_task_runner.py:83} INFO - Job 71: Subtask criando_tabela_bigquery
[2022-10-28T22:29:45.957+0000] {task_command.py:376} INFO - Running <TaskInstance: carga_tb_carteira.criando_tabela_bigquery manual__2022-10-28T22:28:57.533945+00:00 [running]> on host cs-1097450612417-default
[2022-10-28T22:29:46.010+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=Marcelo Henrique
AIRFLOW_CTX_DAG_ID=carga_tb_carteira
AIRFLOW_CTX_TASK_ID=criando_tabela_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T22:28:57.533945+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-28T22:28:57.533945+00:00
[2022-10-28T22:29:46.017+0000] {base.py:71} INFO - Using connection ID 'gcp_conn' for task execution.
[2022-10-28T22:29:46.024+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1642, in execute
    project_id, dataset_id, table_id = bq_hook.split_tablename(
  File "/home/marcelohenriqueleite35/carteira_ativos/env/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2208, in split_tablename
    raise ValueError(f'Expected table name in the format of <dataset>.<table>. Got: {table_input}')
ValueError: Expected table name in the format of <dataset>.<table>. Got: TB_CARTEIRA
[2022-10-28T22:29:46.029+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=carga_tb_carteira, task_id=criando_tabela_bigquery, execution_date=20221028T222857, start_date=20221028T222945, end_date=20221028T222946
[2022-10-28T22:29:46.043+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 71 for task criando_tabela_bigquery (Expected table name in the format of <dataset>.<table>. Got: TB_CARTEIRA; 16470)
[2022-10-28T22:29:46.070+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T22:29:46.085+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
